version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers
      - image: circleci/postgres:11.1
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4
#    environment:
#      - APP_ENV: testing
#      - APP_KEY: base64:jigaIaW1vv9WAh15WdQELPkrD85d1p4L5SK2mUmuLfQ=
#      - APP_URL: http://localhost
    working_directory: ~/repo
    steps:
      - checkout


      - run: sudo apt install -y postgresql-client || true
      - run: apt-get update && apt-get -y install git unzip zlib1g-dev libpq-dev
      - checkout
      - run: docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
      - run: docker-php-ext-install pdo pdo_pgsql zip
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Setup Laravel
          command: cp .env.circleci .env
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # migration, seeding
      - run: php artisan migrate --seed

      # run tests!
      - run: vendor/bin/phpunit
      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true

      - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk
