version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql
      # - image: circleci/postgres:11.1
#    environment:
#      - APP_ENV: testing
#      - APP_URL: http://localhost

    working_directory: ~/repo
    steps:
      - checkout
      # - run: sudo apt install -y postgresql-client || true
      # - checkout
      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install pdo_mysql
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Start database server
          command: |
            sudo service mysql start
            sleep 2
            ps aux | grep mysql
      - run:
          name: Create non-admin user
          command: |
            sudo mysqladmin --user=root password "mRto9Ec1.Gqw"
      - run:
          name: Setup Laravel
          command: cp .env.circleci .env
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        

      # migration, seeding
      - run: php artisan migrate --seed

      # run tests!
      - run: vendor/bin/phpunit
      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true

      - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk
