version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers
      - image: circleci/postgres:11.1
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4
#    environment:
#      - APP_ENV: testing
#      - APP_KEY: base64:jigaIaW1vv9WAh15WdQELPkrD85d1p4L5SK2mUmuLfQ=
#      - APP_URL: http://localhost
    working_directory: ~/repo
    steps:
      - checkout


      - run: sudo apt install -y postgresql-client || true
